EMOTICON_MAP = {
    # Happy & Laughing
    ":-)": "🙂",
    ":)": "🙂",
    ":-]": "🙂",
    ":]": "🙂",
    ":->": "😁",
    ":>": "😁",
    ":-D": "😃",
    ":D": "😃",
    "xD": "😆",
    "XD": "😆",
    "8-)": "😎",
    "8)": "😎",
    ":-3": "😺",
    ":3": "😺",
    # Winking & Playful
    ";-)": "😉",
    ";)": "😉",
    ":-P": "😛",
    ":P": "😛",
    ":-p": "😛",
    ":p": "😛",
    "xP": "😝",
    "XP": "😝",
    "😜": ";-P",  # Reverse map typo prevention if needed, though strictly text to emoji is better
    # Sad & Crying
    ":-(": "🙁",
    ":(": "🙁",
    ":-[": "😞",
    ":[": "😞",
    ":-<": "😔",
    ":<": "😔",
    ":-c": "😖",
    ":c": "😖",
    ":'(": "😢",
    ";-(": "😢",
    "T_T": "😭",
    "T.T": "😭",
    # Surprised & Shocked
    ":-O": "😮",
    ":O": "😮",
    ":-o": "😯",
    ":o": "😯",
    "O_O": "😳",
    "o_o": "😳",
    "0_0": "😳",
    # Annoyed, Skeptical & Neutral
    ">:[": "😡",
    ">:(": "😠",
    ":-/": "😕",
    ":/": "😕",
    ":-\\": "😕",
    ":\\": "😕",
    ":-|": "😐",
    ":|": "😐",
    "-_-": "😑",
    "-_-'": "😓",
    # Love & Affection
    "<3": "❤️",
    "</3": "💔",
    # Other
    "O:-)": "😇",
    "O:)": "😇",
    ">:-)": "😈",
    ">:)": "😈",
}

EMOTICON_SORTED_KEYS = sorted(
    EMOTICON_MAP.keys(),
    key=len,
    reverse=True,
)
